include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.mocks.dart
  errors:
    always_use_package_imports: warning
    avoid_relative_lib_imports: warning
    prefer_single_quotes: warning
    invalid_assignment: warning
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    unused_element: warning
    unused_field: warning
    public_member_api_docs: warning
    always_specify_types: warning
    invalid_annotation_target: ignore
    always_declare_return_types: warning


linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - always_specify_types
    - sort_constructors_first
    - use_super_parameters
    - prefer_single_quotes
    - avoid_unused_constructor_parameters
    - public_member_api_docs
    - avoid_relative_lib_imports
    - always_declare_return_types


